#
# .travis.yml
# =============================================================================
# The Hooke and Jeeves nonlinear unconstrained minimization algorithm.
# Microservice. Version 0.5.9
# =============================================================================
# A Spring Boot-based application, designed and intended to be run
# as a microservice, implementing the nonlinear unconstrained
# minimization algorithm of Hooke and Jeeves.
#
# This is the configuration of the project characteristics
# used by the Travis CI (continuous integration) service
# to rebuild the project on every push and pull request.
#

%YAML 1.1
---

language: generic

os:       linux

dist:     xenial

services: mongodb

before_install:
    - sudo apt-get update

    ## Installing Doxygen to generate API docs for the microservice.
    - sudo apt-get install doxygen

script:
    ## Querying the system for characteristics and available resources.
    - cat /proc/cpuinfo | grep name && echo
                                    && uname -a
                                    && echo
                                    && df -h
                                    && echo
                                    && free

    ## Building the microservice using GNU Make.
    - pwd && ls -al . docs/
          && echo
          && make clean
          && echo
          && ls -al
          && echo
          && make jar
          && doxygen
          && echo
          && ls -al . docs/ log/ target/
          && echo

...

# vim:set nu et ts=4 sw=4:
